### ISSUE TITLE
implementation error

### ISSUE THREAD

**Issue by robertobuti** [htmltiger/node-red-custom-login#1]
Hello , i like use your project because is the solution i looking for.
I have installed the crypto and cookie as need, patched the settings.js and copied the file. In this condition nodered is not working anymore, looking the syslog i see an error :TypeError: cannot read properties of undefinied (reading "lenght")
Any idea what is ? i'm not expert and i need a suggestion on how to solve / debug it .
thank

**Comment by htmltiger** [comment]
the code is somewhere else as "lenght" is not in my code, it should be "length"

**Comment by robertobuti** [comment]
> the code is somewhere else as "lenght" is not in my code, it should be "length"
Sure, my mistake , it's "length", i see is not in the js, however disapper removing the auth procedure, any idea on where could be the problem ?

**Comment by robertobuti** [comment]
hello,
some more information. 
Finally a step over, i have obtained the login form with httpAdminMiddleware: require("./custom-login.js"), in setting.js but i'm unable to have the same with ui, also if configured as suggested.  UI still without login.
I try define httpNodeAuth: require("./custom-login.js") but cause the error before. Any suggestion on how to obtain same login un UI ?
P.S. no error on syslog during nodered boot.

**Comment by htmltiger** [comment]
somewhere around line 504
 ```
   ui: {
        path: "ui",
        middleware: require("./custom-login.js")
    },
```
 try this one for full default config with suggested changes
    
[settings.js.txt](https://github.com/htmltiger/node-red-custom-login/files/14100239/settings.js.txt)

**Comment by robertobuti** [comment]
GREAT, now it's ok, obviously was my mistake, double delcaration in wrong place. thank a lot for cooperation.
regard

**Comment by robertobuti** [comment]
thank
